# Generated by Django 4.0.3 on 2022-03-30 13:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
