# Generated by Django 4.0.3 on 2022-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_scoreboard_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoreboard',
            name='created_at',
            field=models.CharField(max_length=100),
        ),
    ]
