# Generated by Django 4.0.3 on 2022-04-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_extendeduser_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extendeduser',
            name='profile_pic',
            field=models.FileField(default='default.jpg', upload_to='profilepics'),
        ),
    ]
